apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: mywebs.operator.k8s-summit.org
spec:
  group: operator.k8s-summit.org
  scope: Namespaced
  names:
    plural: mywebs
    singular: myweb
    shortNames:
    - web
    kind: MyWeb
    categories:
    - all
  versions:
  - name: v1
    served: true
    storage: true
    subresources: 
      status: {}
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              image:
                type: string
              nodePortNumber:
                type: integer                
            required:
            - image
          status:
            type: object
            properties:
              completed:
                type: boolean
              port:
                type: integer
            required:
            - completed
            - port
    additionalPrinterColumns:
      - name: image
        jsonPath: .spec.image
        type: string
      - name: Port
        type: integer
        jsonPath: .status.port
      - name: age
        jsonPath: .metadata.creationTimestamp
        type: date

